import './js/mobile-menu';
import './js/modal';
import './js/pagination';
import './js/read';
// import './js/weather';
import './js/theme';
import './js/header';
import './js/calendar';
// import './js/sash';
import './js/api';
import './js/get-card-list-popular';
import './js/get-card-list-search';
import './js/get-popular';
import './js/add-to-favorite';
import './js/get-search';
import './js/set-favorites-on-load';
